---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant

platforms:
  - name: instance
    box: debian/bookworm64
    groups:
      - containers

provisioner:
  name: ansible
  options:
    D: true
  inventory:
    group_vars:
      containers:
        netresearch_docker_containers:
          - name: whoami
            image: traefik/whoami
            networks:
              - name: whoami
              - name: traefik
          - name: nginx
            image: nginx
            networks:
              - name: nginx
              - name: traefik

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
