---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true
    pre_build_image: true
    cgroupns: host
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - containers

provisioner:
  name: ansible
  options:
    D: true
  inventory:
    group_vars:
      containers:
        netresearch_docker_containers:
          - name: whoami
            image: traefik/whoami
          - name: nginx
            image: nginx

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
