---
- name: Prepare
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - docker
      - 'requests<2.32.0'

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
