---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Get status of containers"
      loop: "{{ netresearch_docker_containers }}"
      register: status
      community.docker.docker_container_info:
        name: "{{ item.name }}"

    - name: "Container assertions"
      loop: "{{ status.results }}"
      ansible.builtin.assert:
        that:
          - "item.exists"
          - "item.container.State.Status == 'running'"

    - name: Uniquify network names
      ansible.builtin.set_fact:
        network_names: "{{ network_names | default([]) + [ item.1 ] }}"
      with_subelements:
        - "{{ netresearch_docker_containers }}"
        - networks

    - name: "Get status of networks"
      loop: "{{ network_names | flatten | unique }}"
      register: network_status
      community.docker.docker_network_info:
        name: "{{ item.name }}"

    - name: "Network assertions"
      loop: "{{ network_status.results }}"
      ansible.builtin.assert:
        that:
          - "item.exists"