---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Get status of containers"
      loop: "{{ netresearch_docker_containers }}"
      register: status
      community.docker.docker_container_info:
        name: "{{ item.name }}"

    - name: "Present container assertions"
      loop: "{{ status.results }}"
      when: (item.item.state | default('started')) != 'absent'
      ansible.builtin.assert:
        that:
          - "item.exists"
          - "item.exists and item.container.State.Status == 'running'"

    - name: "Absent container assertions"
      loop: "{{ status.results }}"
      when: (item.item.state | default('started')) == 'absent'
      ansible.builtin.assert:
        that:
          - "not item.exists"

    - name: Uniquify network names
      ansible.builtin.set_fact:
        netresearch_docker_containers_network_names: "{{ netresearch_docker_containers_network_names | default([]) + [ item.1 ] }}"
      with_subelements:
        - "{{ netresearch_docker_containers }}"
        - networks
        - skip_missing: true

    - name: "Get status of networks"
      loop: "{{ netresearch_docker_containers_network_names | default([]) | flatten | unique }}"
      register: network_status
      community.docker.docker_network_info:
        name: "{{ item.name }}"

    - name: "Network assertions"
      loop: "{{ network_status.results }}"
      ansible.builtin.assert:
        that:
          - "item.exists"
