---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Get status of containers"
      loop: "{{ netresearch_docker_containers }}"
      register: status
      community.docker.docker_container_info:
        name: "{{ item.name }}"

    - name: "Container assertions"
      loop: "{{ status.results }}"
      ansible.builtin.assert:
        that:
          - "item.exists"
          - "item.container.State.Status == 'running'"
