on: push

jobs:
  molecule:
    name: Run molecule against role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          cache: pip

      # TODO: Remove `requests` version pin https://github.com/ansible-community/molecule-plugins/issues/256
      - run: python3 -m pip install ansible molecule molecule-docker 'requests<2.32.0'

      - run: molecule test

  lint:
    name: Lint role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          cache: pip

      - run: python3 -m pip install ansible ansible-lint yamllint
      - run: ansible-galaxy install -r requirements.yml

      - run: ansible-lint .
