on:
  push:
    tags:
      - "v*"

jobs:
  ansible-galaxy:
    name: Publish on Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name:
        uses: robertdebock/galaxy-action@1.2.1
        with:
          git_branch: main
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
