name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    uses: netresearch/.github/.github/workflows/ansible-galaxy-release.yml@main
    permissions:
      contents: write
    with:
      create-github-release: true
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
